name: Builds

on: [ push ]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

defaults:
  run:
    shell: bash

jobs:
  job:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          lfs: false

      - name: Install dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install ninja

      - name: Install dependencies
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install ninja

      - name: Install dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y ninja-build make gcc-10

      - uses: ilammy/msvc-dev-cmd@v1
        if: startsWith(matrix.os, 'windows')

      - name: Configure
        run: >
          cmake -B build -S $PWD -GNinja -DBUILD_TESTS=ON
      - name: Build
        run: >
          cmake --build build

      - name: Tests
        run: >
          cmake --build build -- test
          

